### PR TITLE
adding Zul'Aman areaIDs

### PR DESCRIPTION
**Pull request by higels**
Two-line change to add Zul'Aman areaID which seems to be 568.

### CODE REVIEW

**Comment by vallantv** [comment]
Haha. I was just working on this today. I didn’t have the zone ID until earlier today. Cheers and thanks!

**Comment by vallantv** [comment]
Would you mind bumping the addon version (1.2.0) and interface version in the toc. If you do that I can just merge and release. Thanks again!

**Comment by higels** [comment]
Will do.

**Comment by higels** [comment]
Done - I think I got it right...

**Comment by vallantv** [comment]
@higels thanks again. I have not been on wow in months and I completely forgot about this. Cheers!

**Pull request merged**
